@host = localhost
@port = 3000
@baseUrl = http://{{host}}:{{port}}
@contentType = application/json


### PlayerController [GET /players]
# Get all players retrieval from data storage
GET {{baseUrl}}/api/players
Content-Type: {{contentType}}


### Get a player by id
# @prompt id
GET {{baseUrl}}/api/players/{{id}}
Content-Type: {{contentType}}


### Create player
POST {{baseUrl}}/api/players
Content-Type: {{contentType}}

{
  "firstname": "John",
  "lastname": "Doe",
  "phoneNumber": "+1123456789"
}